//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flight_booking_website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingsTbl
    {
        public int Id { get; set; }
        public string Outbound_Departure_Airport { get; set; }
        public string Outbound_Departure_Time { get; set; }
        public string Outbound_Arrival_Airport { get; set; }
        public string Outbound_Arrival_Time { get; set; }
        public string Return_Departure_Airport { get; set; }
        public string Return_Departure_Time { get; set; }
        public string Return_Arrival_Airport { get; set; }
        public string Return_Arrival_Time { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Phone_Number { get; set; }
        public string Email_Address { get; set; }
        public int Number_of_Passengers { get; set; }
        public Nullable<int> Passenger_1_Age { get; set; }
        public Nullable<int> Passenger_2_Age { get; set; }
        public Nullable<int> Passenger_3_Age { get; set; }
        public string Mobile_Number { get; set; }
    }
}
