//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flight_booking_website.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlightsBookingsDBEntities : DbContext
    {
        public FlightsBookingsDBEntities()
            : base("name=FlightsBookingsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BookingsTbl> BookingsTbls { get; set; }
        public DbSet<FlightsTbl> FlightsTbls { get; set; }
        public DbSet<UsersTbl> UsersTbls { get; set; }
    }
}
