//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flight_booking_website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersTbl
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public string Password_Salt { get; set; }
    }
}
